// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package storagemocks

import (
	context "context"
	"github.com/yodra/awesome-golang-formation/pkg/domain"

	mock "github.com/stretchr/testify/mock"
)

// MovieRepository is an autogenerated mock type for the MovieRepository type
type MovieRepository struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, movie
func (_m *MovieRepository) Save(ctx context.Context, movie domain.Movie) error {
	ret := _m.Called(ctx, movie)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Movie) error); ok {
		r0 = rf(ctx, movie)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
